<?php

use Illuminate\Database\Seeder;
use App\Preparation;
class PreparationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Preparation::class, 100)->create();
        Preparation::query()->delete();
        Preparation::insert( $this->data());
        
    }

    public function data()
    {
        $companies = App\Company::all();
        $data = $this->data2();
        foreach($data as $key => $row){
            $data[$key]['company_id'] = $companies->random(1)->first()->id;
        }

        return $data;
    }

    public function data2()
    {
        return [
            [ 'id' => 2016, 'descrip' => 'JUGO DE NARANJA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 2021, 'descrip' => 'JUGO DE MN', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 2022, 'descrip' => 'JUGO DE ARROZ', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 2023, 'descrip' => 'JUGO DE MELÓN', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 2024, 'descrip' => 'JUGO DE MANZANA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 2027, 'descrip' => 'BEBIBLE MN', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 2028, 'descrip' => 'ARROZ BLANCO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3030, 'descrip' => 'JUGO DE FRESA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3031, 'descrip' => 'JUGO DE FRESA C/N LECHE EVAPORADA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3032, 'descrip' => 'JUGO DE GUANABANA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3035, 'descrip' => 'JUGO  DE MELON C/N  LECHE  EVAPORADA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3036, 'descrip' => 'JUGO DE  NARANJA 1', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3037, 'descrip' => 'JUGO DE PAPAYA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3038, 'descrip' => 'JUGO  DE PAPAYA  C/N NARANJA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3039, 'descrip' => 'JUGO DE PAPAYA C/N PIÑA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3040, 'descrip' => 'JUGO DE  PAPAYA  C/N PLATANO DE  SEDA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3041, 'descrip' => 'JUGO  DE PIÑA ', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3042, 'descrip' => 'JUGO DE PIÑA  C/N NARANJA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3046, 'descrip' => 'JUGO SURTIDO', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3047, 'descrip' => 'JUGO DE TORONJA', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3048, 'descrip' => 'AVENA  C/N LECHE  Y CHOCOLATE', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3049, 'descrip' => 'AVENA  C/N  CHOCOLATE', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3050, 'descrip' => 'AVENA C/N  COCOA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3051, 'descrip' => 'AVENA  C/N  MARACUYA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3052, 'descrip' => 'AVENA  C/N  MEMBRILLO', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3053, 'descrip' => 'AVENA  C/N  PIÑA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3060, 'descrip' => 'AVENA  C/N  CHOCOLATE', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3061, 'descrip' => 'AVENA  C/N  LECHE', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3066, 'descrip' => 'AVENA  C/N LECHE  Y CHOCOLATE', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3067, 'descrip' => 'AVENA  C/N  LECHE  Y COCOA', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3068, 'descrip' => 'CAFÉ', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3070, 'descrip' => 'AVENA SOLA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3075, 'descrip' => 'CAFE  C/ LECHE  EVAPORADA  ', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3076, 'descrip' => 'COCOA C/ LECHE  EVAPORADA', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3079, 'descrip' => 'LECHE  CON  CHOCOLATE', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3080, 'descrip' => 'LECHE  EVAPORADA C/ QUINUA', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3081, 'descrip' => 'LECHE  EVAPORADA SOLA', 'preparation_type_id' => '3' , 'company_id' => 1 ],
            [ 'id' => 3082, 'descrip' => 'BUTIFARRA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3083, 'descrip' => 'CROQUETA CON ATÚN', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3084, 'descrip' => 'PAN', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3085, 'descrip' => 'PAN C/ HUEVO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3086, 'descrip' => 'PAN C/ JAMON ', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3088, 'descrip' => 'PAN C/ PLATANO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3089, 'descrip' => 'PAN C/ OMELET DE JAMONADA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3092, 'descrip' => 'AVENA CON LECHE EVAPORADA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3093, 'descrip' => 'AVENA  C/ MANZANA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3094, 'descrip' => 'AVENA C/  MANZANA  Y QUINUA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3095, 'descrip' => 'PAN C/ SALCHICHA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3096, 'descrip' => 'PAN C/ TORTILLA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3097, 'descrip' => 'PAN C/ TORTILLA  DE  ESPINACA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3098, 'descrip' => 'PAN C/ ACEITUNA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3099, 'descrip' => 'PAN C/ ATUN', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3100, 'descrip' => 'PAN C/ BISTECK', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3101, 'descrip' => 'PAN C/ CAMOTE', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3102, 'descrip' => 'PAN C/ CHICHARRON DE PRENSA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3103, 'descrip' => 'PAN C/ CHORIZO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3104, 'descrip' => 'PAN C/ HOT DOG', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3105, 'descrip' => 'PAN C/ HUEVO  FRITO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3106, 'descrip' => 'PAN C/ JAMON DEL  PAIS', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3107, 'descrip' => 'PAN C/ JAMONADA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3108, 'descrip' => ' PAN  CON MATEQUILLA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3109, 'descrip' => 'PAN C/ MARGARINA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3110, 'descrip' => 'PAN C/ MERMEALADA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3111, 'descrip' => 'PAN C/ MORTADELA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3112, 'descrip' => 'PAN C/ PALTA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3113, 'descrip' => 'PAN C/ PATE', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3114, 'descrip' => 'PAN C/ POLLO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3115, 'descrip' => 'PAN C/ QUESO FRESCO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3117, 'descrip' => 'PAN C/ MANTECOSO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3118, 'descrip' => 'PAN C/  RELLENO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3119, 'descrip' => 'PAN C/ SALCHICHA  DE HUACHO ', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3120, 'descrip' => 'PAN C/ TOCINO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3121, 'descrip' => 'PAN C/ TORTILLA DE HOT DOG', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3122, 'descrip' => 'SANDWIICHS', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3123, 'descrip' => 'AGUADITO DE POLLO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3127, 'descrip' => 'CAZUELA DE CARNE ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3128, 'descrip' => 'CHUPE DE  MARISCOS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3129, 'descrip' => 'CAZUELA  DE POLLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3131, 'descrip' => 'CHUPE DE  PESCADO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3132, 'descrip' => 'CHUPE DE  QUINUA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3134, 'descrip' => 'CHUPE DE   TRIGO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3135, 'descrip' => 'CONSOME DE CARNE ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3136, 'descrip' => 'CONSOME  DE POLLO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3137, 'descrip' => 'CREMA DE APIO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3138, 'descrip' => 'CREMA DE ARVEJA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3139, 'descrip' => 'CREMA  DE  ESPINACA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3140, 'descrip' => 'CREMA DE  POLLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3141, 'descrip' => 'CREMA DE  POROS Y PAPAS C/ POLLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3142, 'descrip' => 'CREMA DE  VERDURAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3143, 'descrip' => 'CREMA DE  ZANAHORIA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3144, 'descrip' => 'CREMA DE  ZAPALLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3145, 'descrip' => 'DIETA  DE POLLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3146, 'descrip' => 'SANCOCHADO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3148, 'descrip' => 'PUCHERO DE  RES', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3149, 'descrip' => 'SHAMBAR', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3150, 'descrip' => 'SOPA  A LA  MINUTA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3156, 'descrip' => 'SOPA ARLEQUIN NATURAL', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3157, 'descrip' => 'SOPA  CASUELA  DE RES', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3159, 'descrip' => 'SOPA CHAIRO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3160, 'descrip' => 'SOPA  CHILENA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3163, 'descrip' => 'CALDO DE GALLINA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3165, 'descrip' => 'SOPA CHINA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3167, 'descrip' => 'SOPA  CRESI', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3169, 'descrip' => 'SOPA CRIOLLA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3171, 'descrip' => 'SOPA DE ARROZ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3172, 'descrip' => 'SOPA DE AVENA ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3173, 'descrip' => 'SOPA DE  CARNE', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3174, 'descrip' => 'SOPA DE POLLO CON VERDURAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3175, 'descrip' => 'SOPA DE CHOROS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3176, 'descrip' => 'SOPA  CORBATITA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3177, 'descrip' => 'SOPA DE FREJOLES', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3178, 'descrip' => 'SOPA DE  LETRAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3184, 'descrip' => 'SOPA DE  MOTE', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3186, 'descrip' => 'SOPA DE MUNICION  DE POLLO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3196, 'descrip' => 'SOPA DE  OTOÑO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3198, 'descrip' => 'SOPA DE  PESCADO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3200, 'descrip' => 'SOPA DE POLENTA C/VERDURAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3201, 'descrip' => 'SOPA DIETA DE POLLO ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3202, 'descrip' => 'SOPA DE  FIDEOS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3207, 'descrip' => 'SOPA DE QUINUA ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3208, 'descrip' => 'SOPA DE SEMOLA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3209, 'descrip' => 'SOPA DE SEMOLA C/VERDURAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3210, 'descrip' => 'SOPA DE TRIGO C/VERDURAS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3212, 'descrip' => 'SOPA FUCHIFU', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3213, 'descrip' => 'SOPA  JULIANA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3214, 'descrip' => 'SOPA  MENESTRON ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3215, 'descrip' => 'SOPA MENESTRON C/POLLO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3216, 'descrip' => 'SOPA  PATASCA ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3217, 'descrip' => 'SOPA RICA ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3218, 'descrip' => 'SOPA  SECA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3219, 'descrip' => 'SOPA TEOLOGA ', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3220, 'descrip' => 'SOPA  WANTAN', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3221, 'descrip' => 'SUSTANCIA DE  RES', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3224, 'descrip' => 'ANTICUCHOS', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3225, 'descrip' => 'BROCHETA DE POLLO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3227, 'descrip' => 'CAUSA DE  ATÚN ', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3228, 'descrip' => 'CAUSA  LIMEÑA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3229, 'descrip' => 'CAUSA PIONONO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3230, 'descrip' => 'CAUSA RELLENA CON ATÚN Y VERDURAS', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3231, 'descrip' => 'CAUSA RELLENA CON POLLO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3232, 'descrip' => 'CAUSA RELLENA CON POLLO Y PALTA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3233, 'descrip' => 'CAUSA  TRICOLOR', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3234, 'descrip' => 'PRUEBA', 'preparation_type_id' => '17' , 'company_id' => 1 ],
            [ 'id' => 3235, 'descrip' => 'PRUEBA 2', 'preparation_type_id' => '17' , 'company_id' => 1 ],
            [ 'id' => 3236, 'descrip' => 'CEVICHE DE PESCADO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3237, 'descrip' => 'CHOCLO A LA HUANCAINA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3238, 'descrip' => 'CROQUETAS DE ATÚN', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3239, 'descrip' => 'ENSALADA AMERICANA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3240, 'descrip' => 'ENSALADA CÉSAR', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3241, 'descrip' => 'ENSALADA CRUCRUT', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3242, 'descrip' => 'ENSALADA COCIDA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3243, 'descrip' => 'ENSALADA DE FIDEOS', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3244, 'descrip' => 'ENSALADA FRESCA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3245, 'descrip' => 'ENSALADA DE PALTA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3246, 'descrip' => 'ENSALADA DEL CHEF', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3247, 'descrip' => 'ENSALADA PRIMAVERA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3250, 'descrip' => 'ENSALADA RUSA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3251, 'descrip' => 'HUEVO A LA RUSA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3252, 'descrip' => 'HUEVO AL NIDO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3253, 'descrip' => 'HUEVO EN SALSA GOLF', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3254, 'descrip' => 'HUEVO DURO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3256, 'descrip' => 'OCOPA DE MANI', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3257, 'descrip' => 'PALTA RELLENA CON POLLO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3258, 'descrip' => 'PAPA A LA HUANCAINA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3259, 'descrip' => 'CREMA DE PIMIENTO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3260, 'descrip' => 'PAPA RELLENA', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3261, 'descrip' => 'SALPICON DE POLLO', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3262, 'descrip' => 'TAMALITOS', 'preparation_type_id' => '6' , 'company_id' => 1 ],
            [ 'id' => 3263, 'descrip' => 'ADOBO DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3265, 'descrip' => 'AJI DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3266, 'descrip' => 'ARROZ CON POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3267, 'descrip' => 'CARAPULCRA CON POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3268, 'descrip' => 'CEVICHE DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3269, 'descrip' => 'ESCABECHE DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3270, 'descrip' => 'ESTOFADO DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3271, 'descrip' => 'FILETE DE POLLO A LA PLANCHA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3272, 'descrip' => 'FILETE DE POLLO A LA FLORENTINA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3273, 'descrip' => 'POLLO EN SALSA DE CHAMPIÑONES', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3274, 'descrip' => 'FRICASE DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3275, 'descrip' => 'MILANESA DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3276, 'descrip' => 'FILETE DE POLLO AL VAPOR', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3277, 'descrip' => 'POLLADA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3278, 'descrip' => 'POLLO AL VINO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3279, 'descrip' => 'POLLO A LA NARANJA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3280, 'descrip' => 'POLLO A LA OLLA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3281, 'descrip' => 'POLLO A LA PARRILLA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3282, 'descrip' => 'POLLO A LA REYNA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3283, 'descrip' => 'POLLO AL HUACATAY', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3284, 'descrip' => 'POLLO BROASTER', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3285, 'descrip' => 'SECO DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3286, 'descrip' => 'TALLARINES ROJOS CON POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3287, 'descrip' => 'TALLARINES VERDES POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3288, 'descrip' => 'ADOBO DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3290, 'descrip' => 'ASADO DE RES AL JUGO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3291, 'descrip' => 'BISTECK A LO POBRE', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3292, 'descrip' => 'CARNE A LA NORTEÑA', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3293, 'descrip' => 'LOMITO STROGONOF', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3294, 'descrip' => 'LOMO SALTADO DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3296, 'descrip' => 'ATUN', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3297, 'descrip' => 'ATUN A LA VIZCAINA', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3298, 'descrip' => 'ATUN C/ CEBOLLA  Y TOMATE ', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3301, 'descrip' => 'BACALAO A LA ESPAÑOLA', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3302, 'descrip' => 'CAU CAU DE PESCADO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3303, 'descrip' => 'CROQUETA DE ATUN', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3304, 'descrip' => 'JALEA DE PESCADO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3305, 'descrip' => 'PESCADO A LA MENIER', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3306, 'descrip' => 'ARVERJITA PARTIDA', 'preparation_type_id' => '12' , 'company_id' => 1 ],
            [ 'id' => 3308, 'descrip' => 'FRIJOL GUISADO', 'preparation_type_id' => '12' , 'company_id' => 1 ],
            [ 'id' => 3311, 'descrip' => 'LENTEJITAS GUISADAS', 'preparation_type_id' => '12' , 'company_id' => 1 ],
            [ 'id' => 3313, 'descrip' => 'PALLARES GUISADOS', 'preparation_type_id' => '12' , 'company_id' => 1 ],
            [ 'id' => 3314, 'descrip' => 'FIDEO SANCOCHADO ', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3315, 'descrip' => 'LOCRO DE  ZAPALLO', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3316, 'descrip' => 'MAYONESA  CASERA', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3317, 'descrip' => 'MAYONESA DE LECHE', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3318, 'descrip' => 'SALSA BLANCA', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3319, 'descrip' => 'SALSA CRIOLLA', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3320, 'descrip' => 'SALSA SILLAO', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3321, 'descrip' => 'SALSA GOLF', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3322, 'descrip' => 'SALSA MERILAND', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3324, 'descrip' => 'SALSA NAPOLITANA', 'preparation_type_id' => '13' , 'company_id' => 1 ],
            [ 'id' => 3325, 'descrip' => 'REFRESCO DE MARACUYA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3326, 'descrip' => 'REFRESCO', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3327, 'descrip' => 'NARANJADA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3328, 'descrip' => 'CHICHA MORADA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3329, 'descrip' => 'LIMONADA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3330, 'descrip' => 'REFRESCO DE MANZANA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3331, 'descrip' => 'REFRESCO DE PIÑA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3332, 'descrip' => 'REFRESCO DE CARAMBOLA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3333, 'descrip' => 'ARROZ CON LECHE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3334, 'descrip' => 'POSTRE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3335, 'descrip' => 'ARROZ SAMBITO', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3336, 'descrip' => 'COMPOTA DE MANZANA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3337, 'descrip' => 'COMPOTA DE PIÑA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3338, 'descrip' => 'DULCE DE DURAZNO', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3339, 'descrip' => 'MANDARINA POSTRE FRUTA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3340, 'descrip' => 'MANZANA POSTRE FRUTA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3341, 'descrip' => 'ENSALADA DE FRUTAS', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3342, 'descrip' => 'MAZAMORRA DE LECHE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3343, 'descrip' => 'MAZAMORRA DE MANZANA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3344, 'descrip' => 'MAZAMORRA DE MARACUYÁ', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3345, 'descrip' => 'MAZAMORRA DE NARANJA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3347, 'descrip' => 'ARROZ CON PEREJIL', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3348, 'descrip' => 'ARROZ ARVERJADO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3349, 'descrip' => 'ARROZ CON ZANAHORIA', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3350, 'descrip' => 'ARROZ CON CHOCLO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3351, 'descrip' => 'CAMOTE AL HORNO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3352, 'descrip' => 'CAMOTE FRITO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3353, 'descrip' => 'CHOCLO AL VAPOR', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3354, 'descrip' => 'PAPA SANCOCHADA', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3355, 'descrip' => 'PAPAS FRITAS', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3356, 'descrip' => 'PURE DE PAPAS', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3357, 'descrip' => 'PURE DE ESPINACA', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3358, 'descrip' => 'POLLO A LA MOSTAZA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3359, 'descrip' => 'BISTECK MONTADO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3360, 'descrip' => 'LEGUMBRES AL VAPOR', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3361, 'descrip' => 'PAN DE YEMA', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3362, 'descrip' => 'SALAD BAR 1', 'preparation_type_id' => '25' , 'company_id' => 1 ],
            [ 'id' => 3363, 'descrip' => 'SALAD BAR 2', 'preparation_type_id' => '25' , 'company_id' => 1 ],
            [ 'id' => 3364, 'descrip' => 'SALAD BAR 3', 'preparation_type_id' => '25' , 'company_id' => 1 ],
            [ 'id' => 3365, 'descrip' => 'TALLARINES AL PESTO CON BISTECK', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3366, 'descrip' => 'JUGO DE FRESA SODEXO', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3367, 'descrip' => 'CAU CAU DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3368, 'descrip' => 'QUESO FRESCO', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3369, 'descrip' => 'SECO DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3370, 'descrip' => 'TANGELO POSTRE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3371, 'descrip' => 'REFRESCO DE TORONJIL', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3372, 'descrip' => 'SOJA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3373, 'descrip' => 'RES A LA JARDINERA', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3374, 'descrip' => 'PAN CON LOMO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3375, 'descrip' => 'COMPOTA DE NARANJA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3377, 'descrip' => 'REFRESCO DE HIERBA LUISA 1', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3378, 'descrip' => 'PAVITA AL HORNO NAVIDEÑO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3379, 'descrip' => 'PAVO NAVIDEÑO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3380, 'descrip' => 'CARLOTA RUSA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3381, 'descrip' => 'CERDO AL HORNO NAVIDEÑO', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 3383, 'descrip' => 'JUGO DE PAPAYA CON MELON', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 3384, 'descrip' => 'PANETON', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 3385, 'descrip' => 'POLLO ENROLLADO ', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3386, 'descrip' => 'YUCA AL VAPOR', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3387, 'descrip' => 'QUINUA C/N PIÑA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3388, 'descrip' => 'ARROZ TAPADO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3389, 'descrip' => 'PESCADO APANADO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3390, 'descrip' => 'PAVITA A LA CACEROLA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3391, 'descrip' => 'REFRESCO DE TE Y CANELA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3392, 'descrip' => 'BISTECK AL JUGO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3393, 'descrip' => 'PURÉ DE PALLARES', 'preparation_type_id' => '12' , 'company_id' => 1 ],
            [ 'id' => 3394, 'descrip' => 'PUDIN BICOLOR', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3395, 'descrip' => 'SOPA DE TORNILLOS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3396, 'descrip' => 'ESCABECHE DE PESCADO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3397, 'descrip' => 'REFRESCO DE CEDRON', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3398, 'descrip' => 'MACA', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3399, 'descrip' => 'TALLARIN SALTADO CRIOLLO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3400, 'descrip' => 'POLLO AL LIMONKAI', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3401, 'descrip' => 'ARROZ CHAUFA', 'preparation_type_id' => '16' , 'company_id' => 1 ],
            [ 'id' => 3402, 'descrip' => 'REFRESCO DE CEBADA', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3403, 'descrip' => 'POLLO AL HORNO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3404, 'descrip' => 'PICANTE DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3405, 'descrip' => 'MATASQUITA DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3406, 'descrip' => 'SOPA VERDE', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3407, 'descrip' => 'GRANADILLA POSTRE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3408, 'descrip' => 'POLLO A LA JARDINERA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3409, 'descrip' => 'FLAN', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3410, 'descrip' => 'SPAGUETTY A LA BOLOGNESA', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3411, 'descrip' => 'SIETE SEMILLAS', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3412, 'descrip' => 'ENCEBOLLADO DE ATUN', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3413, 'descrip' => 'SOPA DE OLLUCO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3414, 'descrip' => 'CHULETA A LA BBQ', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 3415, 'descrip' => 'MAZAMORRA MORADA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3416, 'descrip' => 'ADOBO DE CERDO', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 3417, 'descrip' => 'SOPA DE CANGREJOS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3418, 'descrip' => 'PESCADO FRITO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3419, 'descrip' => 'PAVITA EN CREMA DE LIMON', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3420, 'descrip' => 'MONDONGUITO A LA ITALIANA', 'preparation_type_id' => '11' , 'company_id' => 1 ],
            [ 'id' => 3422, 'descrip' => 'PAVITA A LA PRIMAVERA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3423, 'descrip' => 'PYE DE MANZANA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3424, 'descrip' => 'ARROZ CON CARNE A LA CHICLAYANA', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3425, 'descrip' => 'OLLUQUITO CON CARNE', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3426, 'descrip' => 'PLATANO SEDA POSTRE', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3427, 'descrip' => 'PESCADO A LA CHORRILLANA', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3428, 'descrip' => 'TALLARINES AL PESTO CON POLLO A LA PLANCHA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3429, 'descrip' => 'SALTADO DE VAINITAS DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3430, 'descrip' => 'CHUPE CRIOLLO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3431, 'descrip' => 'CAU CAU CRIOLLO DE MONDONGO', 'preparation_type_id' => '11' , 'company_id' => 1 ],
            [ 'id' => 3432, 'descrip' => 'ARROZ CON CERDO', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 3433, 'descrip' => 'EMOLIENTE', 'preparation_type_id' => '15' , 'company_id' => 1 ],
            [ 'id' => 3434, 'descrip' => 'HARINA DE HABAS C/N LECHE', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3435, 'descrip' => 'BUDIN DE PAN', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3436, 'descrip' => 'TACU TACU CON LOMO DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 3439, 'descrip' => 'SOPA DE CABELLO DE ANGEL', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3440, 'descrip' => 'POLLO A LA FINAS HIERBAS', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3441, 'descrip' => 'CARAPULCRA DE CERDO', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 3442, 'descrip' => 'GELATINA DE FRESA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3443, 'descrip' => 'SOPA DE KION', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3444, 'descrip' => 'SPAGUETTY A LA HUACAINA CON POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3445, 'descrip' => 'QUINUA C/N LECHE', 'preparation_type_id' => '2' , 'company_id' => 1 ],
            [ 'id' => 3446, 'descrip' => 'LOMITO DE ATÚN', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3448, 'descrip' => 'AEROPUERTO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3449, 'descrip' => 'SOPA DE NOVIOS', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3450, 'descrip' => 'DELICIA DE QUINUA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 3451, 'descrip' => 'POLLO AL MANI', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3452, 'descrip' => 'CALDO DE CABEZA', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 3453, 'descrip' => 'TRUCHA ESTILO HUANCAYO', 'preparation_type_id' => '9' , 'company_id' => 1 ],
            [ 'id' => 3454, 'descrip' => 'LOMO SALTADO DE POLLO', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3455, 'descrip' => 'POLLO CHI JAU KAI', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 3456, 'descrip' => 'MAZAMORRA DE CALABAZA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 4445, 'descrip' => 'JUGO DE MANGO', 'preparation_type_id' => '1' , 'company_id' => 1 ],
            [ 'id' => 4446, 'descrip' => 'AJI DE GALLINA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 4447, 'descrip' => 'ESTOFADO DE RES', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 4448, 'descrip' => 'GARBANZO A LA ESPAÑOLA', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 4449, 'descrip' => 'HAMBURGUESA AL JUGO', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 4450, 'descrip' => 'DULCE DE PIÑA', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 4451, 'descrip' => 'CARBONADA DE TERNERA', 'preparation_type_id' => '8' , 'company_id' => 1 ],
            [ 'id' => 4452, 'descrip' => 'HIGADO ENCEBOLLADO', 'preparation_type_id' => '11' , 'company_id' => 1 ],
            [ 'id' => 4453, 'descrip' => 'CALDILLO DE HUEVO', 'preparation_type_id' => '5' , 'company_id' => 1 ],
            [ 'id' => 4454, 'descrip' => 'ARROZ CHAUFA MIXTO POLLO Y CERDO', 'preparation_type_id' => '10' , 'company_id' => 1 ],
            [ 'id' => 4455, 'descrip' => 'KEKE MARMOLEADO', 'preparation_type_id' => '14' , 'company_id' => 1 ],
            [ 'id' => 4456, 'descrip' => 'MEDALLON DE PAVITA', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            [ 'id' => 4457, 'descrip' => 'PAN C/N MANJAR BLANCO', 'preparation_type_id' => '4' , 'company_id' => 1 ],
            [ 'id' => 4458, 'descrip' => 'PACHAMANCA DOS SABORES', 'preparation_type_id' => '7' , 'company_id' => 1 ],
            
        ];
    }
}
